[package]
name = "discord_game_sdk"
version = "0.2.0"
authors = ["ldesgoui <ldesgoui@gmail.com>"]
edition = "2018"
description = "Safe wrapper for the Discord Game SDK"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/ldesgoui/discord_game_sdk"
keywords = ["discord", "sdk", "gamedev"]
categories = ["api-bindings", "game-engines"]

[package.metadata.docs.rs]
features = ["discord_game_sdk_sys/doc"]

[features]
mock = ["discord_game_sdk_sys/mock", "discord_game_sdk_mock"]

[dependencies]
bitflags = "1.0.4"
chrono = "0.4.6"
crossbeam-channel = "0.3.8"
derive_more = "0.14.0"
easy-ext = "0.1.4"
err-derive = "0.1.5"
log = "0.4.6"
memchr = "2.2.0"
scopeguard = "1.0.0"

[dependencies.discord_game_sdk_sys]
path = "./sys"
version = "0.2.0"

[dependencies.discord_game_sdk_mock]
optional = true
path = "./mock"
version = "0.2.0"

[dev-dependencies]
pretty_env_logger = "0.3.0"

[workspace]
members = ["sys", "mock"]
